extends:
  [
    "eslint:recommended",
    "plugin:mocha/recommended",
    "plugin:@typescript-eslint/recommended",
    "prettier/@typescript-eslint",
    "plugin:prettier/recommended",
  ]
plugins: ["@typescript-eslint", "mocha", "prettier"]
env:
  browser: false
  es6: true
  node: true
  mocha: true
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - avoidEscape: true
      allowTemplateLiterals: true
  semi:
    - error
    - always
  object-curly-spacing:
    - warn
    - always
  "@typescript-eslint/explicit-function-return-type":
    - off
  "@typescript-eslint/camelcase":
    - off
  "mocha/no-mocha-arrows":
    - off
  "mocha/no-setup-in-describe":
    - off
  "@typescript-eslint/no-non-null-assertion":
    - off
